//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBFirstMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class AllocatedRoom
    {
        public int AllocatedRoomID { get; set; }
        public Nullable<int> RequestID { get; set; }
        public string RoomName { get; set; }
        public string Comments { get; set; }
        public Nullable<short> GroupSize { get; set; }
    
        public virtual Request Request { get; set; }
        public virtual Room Room { get; set; }
    }
}
