//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBFirstMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Building
    {
        public Building()
        {
            this.Rooms = new HashSet<Room>();
        }
    
        public string BuildingCode { get; set; }
        public string Building1 { get; set; }
        public string Park { get; set; }
    
        public virtual Park Park1 { get; set; }
        public virtual ICollection<Room> Rooms { get; set; }
    }
}
