//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBFirstMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Degree
    {
        public int DegreeID { get; set; }
        public string DegreeName { get; set; }
        public string DeptCode { get; set; }
        public string Part { get; set; }
    
        public virtual Dept Dept { get; set; }
    }
}
