//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBFirstMVC
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Facility
    {
        public Facility()
        {
            this.FacilityRequests = new HashSet<FacilityRequest>();
            this.RoomFacilities = new HashSet<RoomFacility>();
        }
    
        public int FacilityID { get; set; }
        [Required]
        public string FacilityName { get; set; }
    
        public virtual ICollection<FacilityRequest> FacilityRequests { get; set; }
        public virtual ICollection<RoomFacility> RoomFacilities { get; set; }
    }
}
