//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBFirstMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModuleLecturer
    {
        public int ModuleLecturerID { get; set; }
        public string ModCode { get; set; }
        public int LecturerID { get; set; }
    
        public virtual Lecturer Lecturer { get; set; }
        public virtual Module Module { get; set; }
    }
}
