//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBFirstMVC
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Module
    {
        public Module()
        {
            this.ModuleDegrees = new HashSet<ModuleDegree>();
            this.Requests = new HashSet<Request>();
            this.Lecturers = new HashSet<Lecturer>();
        }
    
        public string ModCode { get; set; }
        [Required]
        public string Title { get; set; }
        public string Part { get; set; }
        public Nullable<short> Students { get; set; }
        public Nullable<byte> Hours { get; set; }
        public Nullable<byte> Weight { get; set; }
        public string DeptCode { get; set; }
    
        public virtual Dept Dept { get; set; }
        public virtual ICollection<ModuleDegree> ModuleDegrees { get; set; }
        public virtual ICollection<Request> Requests { get; set; }
        public virtual ICollection<Lecturer> Lecturers { get; set; }
    }
}
