//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBFirstMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestToRoom
    {
        public int RequsetToRoomID { get; set; }
        public int RequestID { get; set; }
        public int RoomRequestID { get; set; }
    
        public virtual Request Request { get; set; }
        public virtual RoomRequest RoomRequest { get; set; }
    }
}
