//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBFirstMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomRequest
    {
        public RoomRequest()
        {
            this.RequestToRooms = new HashSet<RequestToRoom>();
        }
    
        public int RoomRequestID { get; set; }
        public string RoomName { get; set; }
        public Nullable<short> GroupSize { get; set; }
        public Nullable<byte> PriorityRoom { get; set; }
    
        public virtual ICollection<RequestToRoom> RequestToRooms { get; set; }
        public virtual Room Room { get; set; }
    }
}
