//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBFirstMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room
    {
        public Room()
        {
            this.RoomFacilities = new HashSet<RoomFacility>();
            this.RoomRequests = new HashSet<RoomRequest>();
            this.AllocatedRooms = new HashSet<AllocatedRoom>();
        }
    
        public string RoomName { get; set; }
        public string BuildingCode { get; set; }
        public Nullable<short> Capacity { get; set; }
        public Nullable<byte> Lab { get; set; }
        public string URL { get; set; }
        public string DeptCode { get; set; }
    
        public virtual Building Building { get; set; }
        public virtual Dept Dept { get; set; }
        public virtual ICollection<RoomFacility> RoomFacilities { get; set; }
        public virtual ICollection<RoomRequest> RoomRequests { get; set; }
        public virtual ICollection<AllocatedRoom> AllocatedRooms { get; set; }
    }
}
