//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBFirstMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Week
    {
        public int WeekID { get; set; }
        public Nullable<byte> Week1 { get; set; }
        public Nullable<byte> Week2 { get; set; }
        public Nullable<byte> Week3 { get; set; }
        public Nullable<byte> Week4 { get; set; }
        public Nullable<byte> Week5 { get; set; }
        public Nullable<byte> Week6 { get; set; }
        public Nullable<byte> Week7 { get; set; }
        public Nullable<byte> Week8 { get; set; }
        public Nullable<byte> Week9 { get; set; }
        public Nullable<byte> Week10 { get; set; }
        public Nullable<byte> Week11 { get; set; }
        public Nullable<byte> Week12 { get; set; }
        public Nullable<byte> Week13 { get; set; }
        public Nullable<byte> Week14 { get; set; }
        public Nullable<byte> Week15 { get; set; }
    }
}
